In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
array1=np.array([1,2,3,4])
print(f"array1 has shape {array1.shape} and looks like:")
print(array1)

array1 has shape (4,) and looks like:
[1 2 3 4]


In [ ]:
array2=np.array([[1,5,8],
                [2,6,9]])
print(f"array2 has shape {array2.shape} and looks like:")
print(array2)

array2 has shape (2, 3) and looks like:
[[1 5 8]
 [2 6 9]]


In [ ]:
array3=np.array([
                [[0.1,0.2,4,7],
                 [10,20,0.8,90]],
                [[0.6,100,45,13],
                 [12,85,102,0.3]],
                [[52,23,108,0.2],
                 [78,0.7,25,0.9]]
                ])
print(f"array3 has shape {array3.shape} and looks like:")
print(array3)

array3 has shape (3, 2, 4) and looks like:
[[[1.00e-01 2.00e-01 4.00e+00 7.00e+00]
  [1.00e+01 2.00e+01 8.00e-01 9.00e+01]]

 [[6.00e-01 1.00e+02 4.50e+01 1.30e+01]
  [1.20e+01 8.50e+01 1.02e+02 3.00e-01]]

 [[5.20e+01 2.30e+01 1.08e+02 2.00e-01]
  [7.80e+01 7.00e-01 2.50e+01 9.00e-01]]]


In [ ]:
# To access specific elements in array
print(array1[1:4])

[2 3 4]


In [ ]:
print(array2[0:2,1:3])

[[5 8]
 [6 9]]


In [ ]:
a1=np.array([1,5,3,2,7])
a2=np.array([2,10,20,3,8])
result=a1+a2
print(f"result using numpy arrays: {result}")

result using numpy arrays: [ 3 15 23  5 15]


In [ ]:
# finding dimension of array
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
3


In [ ]:
#creating an array using arange() function
array4=np.arange(1,10)
print(array4)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# using eye() function
array5=np.eye(3,4)
print(array5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
n=np.array([[1,2,3,4],
            [4,6,7,5]])
n1=n.reshape(1,8)
n2=n.reshape(4,2)
n3=n.reshape(8,1)
print(n1)
print(n2)
print(n3)


[[1 2 3 4 4 6 7 5]]
[[1 2]
 [3 4]
 [4 6]
 [7 5]]
[[1]
 [2]
 [3]
 [4]
 [4]
 [6]
 [7]
 [5]]


In [ ]:
x1=np.arange(5,12)
print(x1)

[ 5  6  7  8  9 10 11]


In [ ]:
x2=x1
print(np.shares_memory(x1,x2))

True
